# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f432562323a8a79f30c2573d1cb7ae9c040c5f77ae5251900bd24183a5372eaca634e230aa3b9122b07a19edbcce529826f79bfe7f0936857f5c78aa1e0a4ba

test:
  secret_key_base: 2e43f8513e993e3ce7de978f7aaba46c7dec03c7e9225832d43dcc6ff792328f58ba41a662c4e69c06ab1f4d8e6c6f89386d015a5236627164d4235d6c5cb4c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
